#!/usr/bin/python
import sqlite3
import os
import sys
import time
import datetime
import inspect
from datetime import datetime, timedelta
from random import randint

class MySum:
    def __init__(self):
        self.count = 0

    def step(self, value):
        self.count += value

    def finalize(self):
        return self.count
MySum(3)

sys.exit()

time_now = datetime.now()
time_outdated = time_now - timedelta(hours=1)

print time_now
print time_outdated


if time_now < time_outdated:
    print "outdated"
else:
    print "valid"

time_now = time_now - timedelta(hours=2)

if time_now < time_outdated:
    print "outdated"
else:
    print "valid"

for i in range(100,200):
    print i
